Private REST API and Improved Networking (#3)
* Working private API GW

DynamoDB table is accessed via a VPC Gateway Endpoint, API GW via a VPC Interface Endpoint

* Refactored pipeline to use a single "application" stage

* Refactored API endpoint to be a CfnOutput

* Moved build and deploy image step to web stack pre step

* Refactored API dependency to use an implicit Cfn export

* WebStack resources use NetworkingStack VPC

* Moved build image step to post stateful stack

* Refactor stateless stack to use LambdaIntegration

* Clean up

diff --git a/scripts/destroy_ephemeral b/scripts/destroy_ephemeral
--- a/scripts/destroy_ephemeral
+++ b/scripts/destroy_ephemeral
@@ -1,8 +1,7 @@
 #!/bin/bash
 #
-# Perform a deployment of all application stacks (excludes the pipeline and
-# web stack) to an ephemeral environment, using the current git branch as the
-# namespace.
+# Destroy all application stacks (excludes the pipeline and web stack) to an
+# ephemeral environment, using the current git branch as the namespace.
 
 readonly CYAN="\033[0;36m"
 readonly RED="\033[0;31m"
@@ -14,8 +13,9 @@ branch_name="$(git symbolic-ref HEAD 2>/dev/null)" ||
 [[ -z "$branch_name" ]] && {
   echo -e \
     "${RED}Error: ${NO_COLOUR}" \
-    "Attempting to deploy with detached head, this is a problem because we" \
-    "need a branch name to differentiate ephemeral resources." \
+    "Attempting to destroy ephemeral stacks with detached head, this is a" \
+    "problem because we need a branch name to differentiate ephemeral" \
+    "ephemeral resources." \
     "\nPlease create a feature branch and try again."
   exit 1
 }
@@ -25,10 +25,10 @@ branch_name=${branch_name##refs/heads/}
 if [ "$branch_name" == "main" ]; then
   echo -e \
     "${RED}Error: ${NO_COLOUR}" \
-    "Attempting to deploy via the main branch, this should only be done" \
-    "using the CICD pipeline." \
-    "\nIf you wish to deploy an ephemeral environment that mirrors" \
-    "production, please create a feature branch first." \
+    "Attempting to destroy ephemeral stacks while on the main branch, this " \
+    "is not supported." \
+    "Please checkout a feature branch that has corresponding ephemeral" \
+    "stacks already deployed." \
     "\n${CYAN}See the release strategy doc for more info.${NO_COLOUR}"
   exit 1
 fi
@@ -56,25 +56,24 @@ echo -e "Using prefix: ${CYAN}$PREFIX${NO_COLOUR}"
 # Now we can run cdk deploy, passing in our prefix as context which will
 # appropriately name the stacks we want to deploy. We'll also pass in any
 # additional CLI arguments using $@.
-cdk deploy \
+cdk destroy \
   "${PREFIX}Stage/${PREFIX}NetworkingStack" \
   "${PREFIX}Stage/${PREFIX}StatefulStack" \
   "${PREFIX}Stage/${PREFIX}StatelessStack" \
-  -c ephemeral_prefix="$PREFIX" \
+  -c ephemeral_prefix="${PREFIX}" \
   "$@"
-deploy_status=$?
+destroy_status=$?
 
-# Check if the deployment failed (non-zero exit code)
-if [ $deploy_status -ne 0 ]; then
+# Check if the destroy command failed (non-zero exit code)
+if [ $destroy_status -ne 0 ]; then
   echo -e \
     "\n${RED}Error: ${NO_COLOUR}" \
-    "deploy_ephemeral failed with exit code $deploy_status." \
+    "destroy_ephemeral failed with exit code $destroy_status." \
     "\nSee CDK output above for more information."
-  exit $deploy_status
+  exit $destroy_status
 fi
 
 echo -e \
-  "${RED}Please remember to tear down ephemeral environment stacks when" \
-  "you are done using them!${NO_COLOUR}"
+  "${CYAN}Successfully destroyed ephemeral stacks!${NO_COLOUR}"
 
 exit 0
